# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# ブラケット内の空白は詰める
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

# 行間の調節はルール対象外に
Layout/EmptyLinesAroundClassBody:
  Enabled: false