name: yumkeeper

services:
  # Railsコンテナ
  api:
    build: .
    volumes:
      - .:/app
      - ./log:/app/log
      - public_data:/app/public
      - tmp_data:/app/tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 3

  # Nginxコンテナ
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/log:/var/log/nginx
      - public_data:/app/public
      - tmp_data:/app/tmp
    depends_on:
      api:
        condition: service_healthy # ECSでのデプロイ安定化が目的

volumes:
  postgres_data:
  public_data:
  tmp_data: